# ==============================================================================
# Knock-Knock Portal with Traefik (Automatic HTTPS)
# ==============================================================================

services:
  knock-knock-portal:
    image: ghcr.io/davbauer/knock-knock-portal:main-amd64
    container_name: knock-knock-portal
    restart: unless-stopped

    # Exposed proxy ports (accessible from outside)
    ports:
      - "8000-8010:8000-8010/tcp"
      - "8000-8010:8000-8010/udp"

    volumes:
      - knock_knock_config:/app/config
      - knock_knock_logs:/app/logs

    environment:
      # PLEASE CHANGE: Generate with `htpasswd -nbBC 12 admin YOUR_PASSWORD`
      ADMIN_PASSWORD_BCRYPT_HASH: "$$2y$$12$$iDQ8Gc/g4x0e0qK.CSLLOuhq4m6KIt6J4hRpVrcDvtsfGy/NV431q"
      # PLEASE CHANGE: Generate with `openssl rand -base64 32`
      JWT_SIGNING_SECRET_KEY: "x7XiOu6GdmPW0MGqLsZxbv5xLG4YFdOjdBYlGatvgpQ="
      LOG_LEVEL: "info"
      LOG_FORMAT: "json"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - web
      - backend

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/api/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # PLEASE CHANGE: Set your domain
      - "traefik.http.routers.portal-http.rule=Host(`${DOMAIN:-example.com}`)"
      - "traefik.http.routers.portal-http.entrypoints=web"
      - "traefik.http.routers.portal-http.service=portal"
      # PLEASE CHANGE: Set your domain
      - "traefik.http.routers.portal.rule=Host(`${DOMAIN:-example.com}`)"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.routers.portal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portal.service=portal"
      - "traefik.http.services.portal.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.secure.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.secure.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure.headers.forceSTSHeader=true"
      - "traefik.http.routers.portal.middlewares=secure"

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - knock-knock-portal
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # PLEASE CHANGE: Set your email for Let's Encrypt notifications
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"

    # HTTP/HTTPS (accessible from outside)
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt

    networks:
      - web

networks:
  web:
    driver: bridge
    name: web
  backend:
    driver: bridge

volumes:
  traefik_certs:
    driver: local
  knock_knock_logs:
    driver: local
  knock_knock_config:
    driver: local
