version: '3.8'

services:
  knock-knock-portal:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: knock-knock-portal
    ports:
      - "8000:8000"      # API port
      - "8080:8080"      # Example proxied port
    volumes:
      - ./backend/config.yml:/app/config.yml
      - ./backend/.env:/app/.env
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    restart: unless-stopped
    networks:
      - knock-knock-network

networks:
  knock-knock-network:
    driver: bridge
