services:
  knock-knock-portal:
    image: 'ghcr.io/davbauer/knock-knock-portal:main-amd64'
    ports:
      - '8000:8000'
      - '8080-8099:8080-8099'
    volumes:
      - 'config:/app/config'
      - 'logs:/app/logs'
    environment:
      - 'ADMIN_PASSWORD_BCRYPT_HASH=${ADMIN_PASSWORD_BCRYPT_HASH}'
      - 'JWT_SIGNING_SECRET_KEY=${JWT_SIGNING_SECRET_KEY}'
      - 'LOG_LEVEL=info'
      - 'LOG_FORMAT=json'
    restart: unless-stopped

volumes:
  config:
  logs:

