# Session Management Configuration
session_config:
  default_session_duration_seconds: 3600        # 1 hour
  auto_extend_session_on_connection: true
  maximum_session_duration_seconds: 86400       # 24 hours
  session_cleanup_interval_seconds: 60

# Network Access Control Lists
network_access_control:
  allowed_dynamic_dns_hostnames: []
  permanently_allowed_ip_ranges:
    - "127.0.0.1"              # Localhost
  dns_refresh_interval_seconds: 300

# Proxy Server Configuration
proxy_server_config:
  listen_address: "0.0.0.0"
  admin_api_port: 8000
  connection_timeout_seconds: 30
  max_connections_per_service: 1000
  tcp_buffer_size_bytes: 32768
  udp_buffer_size_bytes: 65507
  udp_session_timeout_seconds: 300

# Real IP Extraction for Proxied Deployments
trusted_proxy_config:
  enabled: false
  trusted_proxy_ip_ranges: []
  client_ip_header_priority:
    - "CF-Connecting-IP"
    - "X-Real-IP"
    - "X-Forwarded-For"

# Portal User Accounts
# Password hash for "password123": $2a$10$hv1bj.Z0tDFRGepS5BvARO.NBrbsXmA8qAD4jnrCdhqeldYRKLbZW
portal_user_accounts:
  - user_id: "550e8400-e29b-41d4-a716-446655440000"
    username: "demo"
    display_username_in_public_login_suggestions: true
    bcrypt_hashed_password: "$2a$10$hv1bj.Z0tDFRGepS5BvARO.NBrbsXmA8qAD4jnrCdhqeldYRKLbZW"
    allowed_service_ids: []  # Empty = all services
    notes: "Demo user with full access"

# Protected Services Definitions
protected_services:
  - service_id: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
    service_name: "Example Service"
    proxy_listen_port_start: 8080
    proxy_listen_port_end: 8080
    backend_target_host: "127.0.0.1"
    backend_target_port: 9000
    transport_protocol: "tcp"
    is_http_protocol: false
    enabled: true
    description: "Example protected service"
